# login-action.yml

name: Docker Login

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      docker_file:
        type: string
        required: true

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up build and push enviroment
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.docker_file }}
          push: true
          tags: ${{ inputs.tag }}
