# login-action.yml

name: Docker Login

on:
  workflow_call:
   secrets:
      username:
        required: true
      token:
        required: true

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
